Repository UMC-7th-DANTHIS/frontend, pull requests merged in 2025-09, with the labels that each got.

#193 fix: 댄서 프로필 페이지 반응형 구현
  src/assets/shape/focusdcirclemobile.svg
  src/common/DancerProfile/ClassTab.tsx
  src/common/DancerProfile/DancerBoard.tsx
  src/common/DancerProfile/IntroduceTab.tsx
  src/common/DancerProfile/Profile.tsx
  src/common/DancerProfile/SidebarMobile.tsx
  src/pages/DancerProfile/DancerProfile.tsx
  src/pages/Signup/Signup4.tsx
Labels: Refactor🛠️

#192 fix: 검색 / 홈 / 커뮤니티 반응형에 맞게 구조 수정
  package-lock.json
  src/api/api.ts
  src/assets/buttons/starlevel_filled.svg
  src/assets/buttons/starlevel_nonfilled.svg
  src/common/Comunity/CommunityList.tsx
  src/common/Comunity/EditContent.tsx
  src/common/Comunity/EditFooter.tsx
  src/common/Comunity/ListTopBar.tsx
  src/common/Comunity/PostComment.tsx
  src/common/Comunity/PostContent.tsx
  src/common/Home/Carousel.tsx
  src/common/Home/ForClass.tsx
  src/common/Home/ForDancer.tsx
  src/common/Home/ForUserBanner.tsx
  src/common/Home/HotDancerBanner.tsx
  src/common/Home/PassiveCarousel.tsx
  src/common/Search/SearchBar.tsx
  src/common/Search/SearchClass.tsx
  src/common/Search/SearchCommunity.tsx
  src/common/Search/SearchDancer.tsx
  src/common/Search/SearchNothing.tsx
  src/components/Footer.tsx
  src/components/Pagination.tsx
  src/components/topbar/Topbar.tsx
  src/hooks/useGetComment.ts
  src/hooks/useSearch.ts
  src/layout/SearchLayout.tsx
  src/layout/SearchWrapper.tsx
  src/pages/Community/CommunityEdit.tsx
  src/pages/Community/CommunityPostPage.tsx
  src/pages/Community/CommunityPut.tsx
  src/pages/CommunityPage.tsx
  src/pages/Home/HotClass.tsx
  src/pages/Home/HotDancer.tsx
  src/pages/Home/UserRecommend.tsx
  src/pages/HomePage.tsx
  src/types/CommunityInterface.ts
Labels: Feat🤗, Refactor🛠️

#196 fix: 모바일 환경에서 레이아웃 오른쪽 여백 제거
  package-lock.json
  package.json
  src/components/topbar/TopbarMenuMobile.tsx
  src/index.css
Labels: Bug🚨

#222 feat: 수업 예약 페이지 날짜/요일별 조회 API 수정 및 일부 디자인 QA 반영
  package-lock.json
  package.json
  src/api/reservation.ts
  src/common/DancerProfile/ClassTab.tsx
  src/common/Home/ForClass.tsx
  src/common/Home/PassiveCarousel.tsx
  src/common/reservation/ClassesGrid.tsx
  src/common/reservation/DateTypeToggle.tsx
  src/common/reservation/SelectionPanel.tsx
  src/common/reservation/WeeklySelector.tsx
  src/components/Calendar.tsx
  src/components/ScrollToTop.tsx
  src/components/Skeleton.tsx
  src/hooks/reservation/useGetClasses.ts
  src/index.css
  src/index.tsx
  src/pages/reservation/ReservationPage.tsx
  src/store/dateSelectionStore.ts
  src/types/common.ts
  src/types/reservation.ts
Labels: Feat🤗
